// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.PostList = (function(_super) {

    __extends(PostList, _super);

    function PostList() {
      return PostList.__super__.constructor.apply(this, arguments);
    }

    PostList.prototype.model = app.Post;

    PostList.prototype.comparator = function(post) {
      return -post.get('created_time');
    };

    PostList.prototype.sync = function(method, model, options) {
      return FB.api('/me/home', function(data) {
        return options.success(data.data);
      });
    };

    return PostList;

  })(Backbone.Collection);

}).call(this);
