// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.Post = (function(_super) {

    __extends(Post, _super);

    function Post() {
      return Post.__super__.constructor.apply(this, arguments);
    }

    Post.prototype.sync = function(method, model, options) {
      var _this = this;
      return FB.api(this.get('id'), function(data) {
        var key, value;
        for (key in data) {
          value = data[key];
          _this.set(key, value);
        }
        console.log(data);
        return options.success(data.data);
      });
    };

    Post.prototype.like = function() {
      var _this = this;
      if (!this.get('likes')) {
        this.set('likes', {
          data: []
        });
      }
      this.get('likes')['data'].push({
        id: app.me.id,
        name: app.me.name
      });
      this.trigger('change');
      return FB.api("/" + (this.get('id')) + "/likes", "post", {}, function(response) {
        if (!response) {
          _this.get('likes')['data'].pop();
          return _this.trigger('change');
        }
      });
    };

    return Post;

  })(Backbone.Model);

}).call(this);
