// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.views.Post.Twitter = (function(_super) {

    __extends(Twitter, _super);

    function Twitter() {
      return Twitter.__super__.constructor.apply(this, arguments);
    }

    Twitter.prototype.mentionName = function() {
      var _ref;
      return "@" + ((_ref = this.recipient()) != null ? _ref.replace(" ", "") : void 0);
    };

    Twitter.prototype.twittifiedName = function() {
      var _ref;
      return "@" + ((_ref = this.name()) != null ? _ref.replace(" ", "") : void 0);
    };

    return Twitter;

  })(app.views.Post);

}).call(this);
