// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.views.Post['4chan'] = (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    _Class.prototype.commentsAndLikes = function() {
      var content;
      content = _Class.__super__.commentsAndLikes.apply(this, arguments);
      if (this.isDetailView) {
        return content;
      } else {
        return content.slice(0, 3);
      }
    };

    _Class.prototype.hiddenContent = function() {
      return this.likes().length + this.comments().length > 3;
    };

    _Class.prototype.hiddenCommentCount = function() {
      var commentCount;
      commentCount = this.comments().length || 0;
      if (commentCount === 0) {
        return "0 comments";
      } else if (commentCount === 1) {
        return "1 comment";
      } else {
        return "" + commentCount + " comments";
      }
    };

    _Class.prototype.hiddenLikeCount = function() {
      var commentCount, likeCount;
      commentCount = this.comments().length;
      likeCount = this.likes().length || 0;
      if (likeCount === 0) {
        return "0 likes";
      } else if (commentCount > 3) {
        return "" + likeCount + " likes";
      } else if (commentCount > 0) {
        return "" + (likeCount - (3 - commentCount)) + " likes";
      } else {
        return "" + (likeCount - 3) + " likes";
      }
    };

    _Class.prototype.beforeRender = function() {
      var $parent;
      if (this.isDetailView) {
        $parent = $("#content");
        $parent.html('');
        return this.$el.appendTo($parent);
      }
    };

    return _Class;

  })(app.views.Post);

}).call(this);
