// Generated by CoffeeScript 1.3.3
(function() {
  var bootstrap,
    _this = this;

  window.app = {};

  $.get('templates/4chan/site.html?callback=', function(data) {
    ich.addTemplate('site', data);
    bootstrap();
    return $.get('templates/4chan/stylesheets.html?callback=', function(data) {
      return $('head').append(data);
    });
  });

  bootstrap = function() {
    return $("body").html(ich.site);
  };

}).call(this);
