// Generated by CoffeeScript 1.3.3
(function() {
  var _this = this;

  require(['jquery', 'backbone'], function($, Backbone) {
    var bootstrap;
    $.get('templates/4chan/site.html?callback=', function(data) {
      ich.addTemplate('site', data);
      return bootstrap();
    });
    $.get('templates/4chan/stylesheets.html?callback=', function(data) {
      return $('head').append(data);
    });
    return bootstrap = function() {
      return $("body").html(ich.site);
    };
  });

}).call(this);
