// Generated by CoffeeScript 1.3.3
(function() {
  var checkIfFinishedLoading, networkCount, registerTemplate;

  window.app = {
    views: {}
  };

  networkCount = 0;

  registerTemplate = function(service, name) {
    return $.ajax("templates/" + service + "/" + name + ".html", {
      success: function(data) {
        return ich.addTemplate(name, data);
      },
      complete: function() {
        return checkIfFinishedLoading();
      }
    });
  };

  checkIfFinishedLoading = function() {
    var _ref;
    networkCount--;
    if (networkCount === 0) {
      if ((_ref = app.list) != null) {
        _ref.view.el = document.getElementById("content");
      }
      return app.router.refresh();
    }
  };

  app.loadTheme = function(service) {
    var $fbRoot, view, _i, _len, _ref,
      _this = this;
    if (service !== 'Twitter' && service !== '4chan' && service !== 'welcome') {
      return;
    }
    ich.clearAll();
    $fbRoot = $("#fb-root");
    _ref = ['post', 'comment', 'like', 'loading', 'intro', 'inlineLoading', 'user'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      view = _ref[_i];
      networkCount++;
      registerTemplate(service, view);
    }
    networkCount++;
    $.get("templates/" + (service.toLowerCase()) + "/site.html", function(data) {
      ich.addTemplate('site', data);
      $("body").html(ich.site);
      $("body").append($fbRoot);
      if (service !== 'welcome') {
        new app.views.Buttons().render();
      }
      return $.get("templates/" + (service.toLowerCase()) + "/stylesheets.html", function(data) {
        checkIfFinishedLoading();
        return $('body').append(data);
      });
    });
    return app.theme = service;
  };

  app.showLoading = function() {
    return app.showStatic('loading');
  };

  app.showPartialLoading = function() {
    return $("#content").prepend(ich.inlineLoading());
  };

  app.showStatic = function(name) {
    return $("#content").html(typeof ich[name] === "function" ? ich[name]() : void 0);
  };

  app.showIntro = function() {
    return app.loadTheme('welcome');
  };

  app.params = function() {
    var key, params, setter, setters, value, _i, _len, _ref;
    if (!params) {
      setters = window.location.search.slice(1).split('&');
      params = {};
      for (_i = 0, _len = setters.length; _i < _len; _i++) {
        setter = setters[_i];
        _ref = setter.split('='), key = _ref[0], value = _ref[1];
        params[key] = value;
      }
    }
    return params;
  };

  app.renderList = function() {
    if (app.list != null) {
      app.list.view.render();
      app.showPartialLoading();
    } else {
      app.showLoading();
      app.list = new app.PostList;
      app.list.view = new app.views.PostList({
        model: app.list
      });
    }
    return app.list.fetch({
      success: function() {
        return app.list.view.render();
      }
    });
  };

  app.renderItem = function(item) {
    var view;
    view = new app.views.Post[app.theme]({
      model: item,
      isDetailView: true
    });
    return view.render();
  };

  app.renderItemWithId = function(id) {
    var item;
    app.showLoading();
    item = new app.Post({
      id: id
    });
    return item.fetch({
      success: function() {
        return app.renderItem(item);
      }
    });
  };

}).call(this);
