// Generated by CoffeeScript 1.3.3
(function() {
  var router;

  router = Backbone.Router.extend({
    routes: {
      "": "home",
      "post/:id": "post"
    },
    home: function() {
      return app.renderList();
    },
    post: function(post) {
      return app.renderItemWithId(post);
    },
    refresh: function() {
      var currentRoute;
      currentRoute = Backbone.history.fragment;
      this.navigate('not a valid route');
      return this.navigate(currentRoute, {
        trigger: true
      });
    }
  });

  window.app.router = new router();

}).call(this);
