// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.views.Buttons = (function(_super) {

    __extends(Buttons, _super);

    function Buttons() {
      return Buttons.__super__.constructor.apply(this, arguments);
    }

    Buttons.prototype.id = "buttons";

    Buttons.prototype.render = function() {
      var viewName, _i, _len, _ref;
      _ref = ['Toggle', 'Refresh'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        viewName = _ref[_i];
        new app.views[viewName]().render().appendTo(this.$el);
      }
      return this.$el.appendTo("body");
    };

    return Buttons;

  })(Backbone.View);

}).call(this);
