// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.views.Like = (function(_super) {

    __extends(Like, _super);

    function Like() {
      return Like.__super__.constructor.apply(this, arguments);
    }

    Like.prototype.name = function() {
      return this.model.get('name');
    };

    Like.prototype.uid = function() {
      return this.model.get('id');
    };

    Like.prototype.render = function() {
      var html;
      html = ich.like(this);
      return this.$el.html(html);
    };

    return Like;

  })(app.views.Post);

}).call(this);
