// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  $.get('templates/4chan/post.html', function(data) {
    return ich.addTemplate('post', data);
  });

  app.views.Post = (function(_super) {

    __extends(Post, _super);

    function Post() {
      return Post.__super__.constructor.apply(this, arguments);
    }

    Post.prototype.render = function() {
      var html;
      html = ich.post(this.model);
      return this.$el.html(html);
    };

    return Post;

  })(Backbone.View);

}).call(this);
