// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.views.Toggle = (function(_super) {

    __extends(Toggle, _super);

    function Toggle() {
      return Toggle.__super__.constructor.apply(this, arguments);
    }

    Toggle.prototype.id = "toggle";

    Toggle.prototype.tagName = "button";

    Toggle.prototype.events = {
      click: "toggleTheme"
    };

    Toggle.prototype.toggleTheme = function() {
      return app.loadTheme(this.otherTheme());
    };

    Toggle.prototype.otherTheme = function() {
      if (app.theme === "4chan") {
        return "Twitter";
      } else {
        return "4chan";
      }
    };

    Toggle.prototype.render = function() {
      return this.$el.html("Switch to " + (this.otherTheme()));
    };

    return Toggle;

  })(Backbone.View);

}).call(this);
