// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  app.views.User = (function(_super) {

    __extends(User, _super);

    function User() {
      return User.__super__.constructor.apply(this, arguments);
    }

    User.prototype.el = function() {
      return document.getElementById('user');
    };

    User.prototype.render = function() {
      var html;
      if (ich.user != null) {
        html = ich.user(this);
        return this.$el.html(html);
      }
    };

    User.prototype.name = function() {
      return this.model.get('name');
    };

    User.prototype.avatar = function() {
      return "https://graph.facebook.com/" + (this.model.get('id')) + "/picture";
    };

    return User;

  })(Backbone.View);

}).call(this);
